server:
  port: ${SERVER_PORT:8080}

grpc:
  client:
    cplusplus-server:
      address: 'static://localhost:${SWITCH_AUTO_CORE_PORT:50051}'
      negotiation-type: plaintext
    GLOBAL:
      negotiation-type: plaintext

# 设置单个文件的最大限制
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${SWITCH_AUTO_DB_PATH}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.github.churunfa.switchautoweb.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
